global_exclude_dirs:
    - vendor
    - vendors
    - test
    - tests
    - tests
    - lib/vendor

exclude_patterns:
    - app/check.php
    - app/SymfonyRequirements.php
    - web/config.php
    - web/app_*.php
