<?php

namespace AppBundle\Entity;
use Doctrine\ORM\EntityRepository;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends EntityRepository
{
    public function findAllOrderedByTitle(){
//        $query = $this->getEntityManager()
//            ->createQuery(
//                'Select b FROM AppBundle:Book b ORDER BY b.title ASC'
//            );
            $query = $this->createQueryBuilder('b')
                ->orderBy('b.title', 'ASC')
                ->getQuery();
        return $query->getResult();
    }

}
